version: '3.9'
services:
  postgres:
    build: back/migrations/sqls
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U root
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    image: 'node:14.0.0-alpine'
    command: 'sh -c "yarn run start:dev"'
    working_dir: /app
    ports:
      - '8080:8080'
    volumes:
      - './back:/app'
  client_web:
    depends_on:
      - server
    build:
      context: ./client_web
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
    stdin_open: true
    volumes:
      - ./client_web:/app
      - /app/node_modules

volumes:
  postgres-data: null
  apk: null
