version: "3.9"
services:
  back:
    image: "node:14.0.0-alpine"
    command: sh -c "yarn run start:dev"
    working_dir: /app
    ports:
      - "127.0.0.1:3030:3030"
    volumes:
      - ./back:/app

  postgres:
    image: "postgres:12-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "127.0.0.1:5432:5432"
volumes:
  postgres-data: null
