version: '3.9'
services:
  postgres:
    restart: always
    build: back/migrations/sqls
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U root
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: back
      target: production
    working_dir: /app
    ports:
      - '8080:8080'
    volumes:
      - './back:/app'
      - /app/node_modules
  client_mobile:
    build: client_mobile/
    container_name: client_mobile
    volumes:
      - 'apk:/build/app/outputs/flutter-apk'
  client_web:
    restart: always
    depends_on:
      - server
      - client_mobile
    build: client_web/
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
    volumes:
      - 'apk:/public'
volumes:
  postgres-data: null
  apk: null
