name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test docker-compose build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Running docker-compose build
    - run: docker-compose build
    - name: Connection to remote SSH and deployment
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          rm -rf fake-area
          git clone git@github.com:Nathaniael/fake-area.git
          cd fake-area
          docker-compose up --build -d
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASSWORD}}
