name: remote ssh command
on: [push]
jobs:
  test:
    name: Test build and deploy
    runs-on: ubuntu-latest
    steps:
    #- name: Check out repository code before deployment
     # uses: actions/checkout@v2
    #- run: docker-compose build
    - name: Connection to remite
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          rm -rf area
          git clone git@github.com:Nathaniael/area.git
          cd area
          docker-compose up --build -d
        host: ${{ secrets.HOST }}
        user: debian
        pass: ${{ secrets.PASSWORD}}
